apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: mediator-default
  namespace: gameon-system
spec:
  websocketUpgrade: true
  destination:
    name: mediator
  route:
  - weight: 100
